### ISSUE TITLE
Inloggningsproblem

### ISSUE THREAD

**Issue by danduc999** [bjorkgard/public-secretary#22]
### Beskriv felet

Du får nog radera det kontot jag skapade på dev.jwapp
Har hamnat i ett skumt läge iom att jag inte fått verifieringsmailet och kan inte heller komma åt att skicka verifieringsmailet igen. Försökt återställa lösenordet men eftersom kontot aldrig blivit verifierat/aktiverat funkar inte det

### Hur uppstår felet

Kan inte aktivera kontot

### Systeminformation

```Shell
Mac OS
```

### Bekräftelser

- [X] Följ vår [uppförandekod](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] Kontrollera att det inte redan finns ett problem som rapporterar samma bugg för att undvika att skapa en dubblett.
- [X] Kontrollera att detta är en konkret bugg. För frågor och svar, öppna en GitHub-diskussion istället.
- [X] Beskrivningen är en komplett beskrivning hur felet uppstår.

**Comment by bjorkgard** [comment]
@danduc999 Jag har gjort en liten uppdatering för att komma runt det här problemet. Jag har raderat ditt konto så du behöver registrera dig på nytt.
