### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by danduc999** [bjorkgard/public-secretary#23]
### Beskriv felet

Har aktiverat 2FA men vid inloggning frågar applikationen inte efter 2FA

### Hur uppstår felet

Har aktiverat 2FA men vid inloggning frågar applikationen inte efter 2FA

### Systeminformation

```Shell
Mac
```

### Bekräftelser

- [X] Följ vår [uppförandekod](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] Kontrollera att det inte redan finns ett problem som rapporterar samma bugg för att undvika att skapa en dubblett.
- [X] Kontrollera att detta är en konkret bugg. För frågor och svar, öppna en GitHub-diskussion istället.
- [X] Beskrivningen är en komplett beskrivning hur felet uppstår.

**Comment by danduc999** [comment]
Använder 2FAS Auth..

**Comment by bjorkgard** [comment]
Denna är åtgärdad i version 0.7
